/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.followme;

import it.unicam.cs.followme.app.MessageUtils;
import it.unicam.cs.followme.app.app.MessageUtils;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {
        Assertions.assertEquals("Hello      World!", MessageUtils.getMessage());
    }
}
